version: "1.0"
info:
  model: int-scaffold
packages:
- name: EdgeJcTest
  gitServerName: johnpcarter
  gitUrl: https://github.com/johnpcarter/EdgeJcTest
  gitUsername: johnpcarter
  gitToken: edge.scaffolding.EdgeJcTest.johnpcarter.gitToken
  gitBranch: main
